---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: Function
metadata:
  name: ai-dev
  namespace: dash-ai
  labels:
    dash.ulagbulag.io/alias: ai-development-framework
spec:
  input:
    - name: /gpus/
      integer:
        default: 1
    - name: /image/
      oneOfStrings:
        choices:
          - pytorch
          - tensorflow
        default: pytorch
    - name: /ip/
      ip: {}
    - name: /user/password/
      string:
        dynamic: {}
    - name: /storage/class/
      string:
        default: ceph-block
        dynamic: {}
    - name: /storage/volume/
      string:
        default: 1Ti
        dynamic: {}
    - name: /vnc/enabled/
      boolean:
        default: false
  actor:
    job:
      source:
        configMapRef:
          name: ai-dev
          path: ai-dev.yaml.j2
