---
apiVersion: dash.ulagbulag.io/v1alpha1
kind: Function
metadata:
  name: ai-dev
  namespace: dash-ai
  labels:
    dash.ulagbulag.io/alias: ai-development-framework
spec:
  input:
    - name: /gpus/
      integer:
        default: 1
    - name: /image/
      oneOfStrings:
        choices:
          - pytorch
          - tensorflow
        default: pytorch
    - name: /ip/
      ip: {}
    - name: /namespace/
      string:
        default: dash-ai
        dynamic: {}
    - name: /user/name/
      string:
        dynamic: {}
    - name: /user/password/
      string:
        dynamic: {}
  actor:
    job:
      source:
        configMapRef:
          name: ai-dev
          path: ai-dev.yaml.j2
